### ISSUE TITLE
[FEATURE] 게임  화면 (GameView) 구현

### ISSUE THREAD

**Issue by Skipancho** [Skipancho/game2048#1]
## 📝  To-do

- [x] 배경 화면 구현
- [x] 숫자 블록 구현
- [x] 터치 이벤트 구현
